name: humble-devel

on:
  pull_request:
    branches:
      - humble-devel
  push:
    branches:
      - humble-devel
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
      - name: Fix pip
        run: pip3 install empy==3.3.4; pip3 install -U colcon-common-extensions
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@0.7.15
      - name: build and test
        uses: ros-tooling/action-ros-ci@0.4.5
        with:
          package-name: br2_basics br2_bt_bumpgo br2_bt_patrolling br2_fsm_bumpgo_cpp br2_fsm_bumpgo_py br2_navigation br2_tf2_detector br2_tiago br2_tracking br2_tracking_msgs br2_vff_avoidance
          ref: humble-devel
          target-ros2-distro: humble
          vcs-repo-file-url: ${GITHUB_WORKSPACE}/third_parties.repos
          colcon-defaults: |
            {
              "test": {
                "parallel-workers" : 1
              }
            }
